version: "3"

services:
  web:
    container_name: "web"
    build:
      dockerfile: "./docker/web/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/html"

  app:
    container_name: "app"
    build:
      dockerfile: "./docker/php/Dockerfile"
    volumes:
      - "./src:/var/www/html"

  db:
    container_name: "db"
    build:
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qweqwe
      MYSQL_DATABASE: laravel
    volumes:
      - ./docker/db/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    # platform: linux/amd64
    container_name: phpmyadmin
    ports:
      - 8089:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: qweqwe
      PMA_HOST: db
    depends_on:
      - db

  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
